export interface SubscriptionInfo {
  plan: string;
  active: boolean;
  on_trial: boolean;
  pending_cancelation: boolean;
  renewal_date: string;
  features: {
    EXPORT_CREDITS: {
      name: "Export credits";
      consumed: number;
      remaining: number;
      total: number;
    };
    SCRAPING_SPEED: {
      name: "Scraping speed";
      value: string;
    };
    SEARCH_CITY: {
      name: "Search by city";
      value: boolean;
    };
    SEARCH_ADMIN2_CODE: {
      name: "Search by level 2 division";
      value: boolean;
    };
    SEARCH_ADMIN1_CODE: {
      name: "Search by level 1 division";
      value: boolean;
    };
    SEARCH_WHOLE_COUNTRY: {
      name: "Search on whole country";
      value: boolean;
    };
    ESSENTIAL_SEARCH_FILTERS: {
      name: "Essential search filters";
      value: boolean;
    };
    ADVANCED_SEARCH_FILTERS: {
      name: "Advanced search filters";
      value: boolean;
    };
    GMAP_EXPORT_ADDITIONAL_FIELDS: {
      name: "GMap additional fields in exports";
      value: boolean;
    };
    WEB_EXPORT_ADDITIONAL_FIELDS: {
      name: "Website additional fields in exports";
      value: boolean;
    };
    API_ACCESS: {
      name: "API Access";
      value: boolean;
    };
  };
}

export interface GType_OR_GLocation {
  id: string;
  text: string;
}

export interface OnePlace {
  google_id: string;
  name: string;
  types: {
    type: string;
    deleted: boolean;
    is_main: boolean;
  }[];
  is_closed: boolean;
  descriptions: string[];
  website: string;
  phone: string;
  phone_international: string;
  timezone: string;
  location_full_address: string;
  location_borough: string;
  location_street_1: string;
  location_street_2: string;
  location_city: string | null;
  location_postal_code: string | null;
  location_state: string;
  location_latitude: string;
  location_longitude: string;
  location_country_code: string;
  location_admin1_code: string;
  location_admin2_code: string | null;
  link: string;
  place_id: string;
  owner_name: string;
  owner_id: string;
  price_range: string | null;
  reviews_id: string;
  reviews_count: number;
  reviews_rating: number;
  reviews_per_score: {
    "1": number;
    "2": number;
    "3": number;
    "4": number;
    "5": number;
  };
  photos_count: string;
  photos: any;
  characteristics: any;
  occupancy: {
    monday: {
      "4 AM": string;
      "5 AM": string;
      "6 AM": string;
      "7 AM": string;
      "8 AM": string;
      "9 AM": string;
      "10 AM": string;
      "11 AM": string;
      "12 PM": string;
      "1 PM": string;
      "2 PM": string;
      "3 PM": string;
      "4 PM": string;
      "5 PM": string;
      "6 PM": string;
      "7 PM": string;
      "8 PM": string;
      "9 PM": string;
      "10 PM": string;
      "11 PM": string;
      "12 AM": string;
      "1 AM": string;
      "2 AM": string;
      "3 AM": string;
    };
    tuesday: {
      "4 AM": string;
      "5 AM": string;
      "6 AM": string;
      "7 AM": string;
      "8 AM": string;
      "9 AM": string;
      "10 AM": string;
      "11 AM": string;
      "12 PM": string;
      "1 PM": string;
      "2 PM": string;
      "3 PM": string;
      "4 PM": string;
      "5 PM": string;
      "6 PM": string;
      "7 PM": string;
      "8 PM": string;
      "9 PM": string;
      "10 PM": string;
      "11 PM": string;
      "12 AM": string;
      "1 AM": string;
      "2 AM": string;
      "3 AM": string;
    };
    wednesday: {
      "4 AM": string;
      "5 AM": string;
      "6 AM": string;
      "7 AM": string;
      "8 AM": string;
      "9 AM": string;
      "10 AM": string;
      "11 AM": string;
      "12 PM": string;
      "1 PM": string;
      "2 PM": string;
      "3 PM": string;
      "4 PM": string;
      "5 PM": string;
      "6 PM": string;
      "7 PM": string;
      "8 PM": string;
      "9 PM": string;
      "10 PM": string;
      "11 PM": string;
      "12 AM": string;
      "1 AM": string;
      "2 AM": string;
      "3 AM": string;
    };
    thursday: {
      "4 AM": string;
      "5 AM": string;
      "6 AM": string;
      "7 AM": string;
      "8 AM": string;
      "9 AM": string;
      "10 AM": string;
      "11 AM": string;
      "12 PM": string;
      "1 PM": string;
      "2 PM": string;
      "3 PM": string;
      "4 PM": string;
      "5 PM": string;
      "6 PM": string;
      "7 PM": string;
      "8 PM": string;
      "9 PM": string;
      "10 PM": string;
      "11 PM": string;
      "12 AM": string;
      "1 AM": string;
      "2 AM": string;
      "3 AM": string;
    };
    friday: {
      "4 AM": string;
      "5 AM": string;
      "6 AM": string;
      "7 AM": string;
      "8 AM": string;
      "9 AM": string;
      "10 AM": string;
      "11 AM": string;
      "12 PM": string;
      "1 PM": string;
      "2 PM": string;
      "3 PM": string;
      "4 PM": string;
      "5 PM": string;
      "6 PM": string;
      "7 PM": string;
      "8 PM": string;
      "9 PM": string;
      "10 PM": string;
      "11 PM": string;
      "12 AM": string;
      "1 AM": string;
      "2 AM": string;
      "3 AM": string;
    };
    saturday: {
      "4 AM": string;
      "5 AM": string;
      "6 AM": string;
      "7 AM": string;
      "8 AM": string;
      "9 AM": string;
      "10 AM": string;
      "11 AM": string;
      "12 PM": string;
      "1 PM": string;
      "2 PM": string;
      "3 PM": string;
      "4 PM": string;
      "5 PM": string;
      "6 PM": string;
      "7 PM": string;
      "8 PM": string;
      "9 PM": string;
      "10 PM": string;
      "11 PM": string;
      "12 AM": string;
      "1 AM": string;
      "2 AM": string;
      "3 AM": string;
    };
    sunday: {
      "4 AM": string;
      "5 AM": string;
      "6 AM": string;
      "7 AM": string;
      "8 AM": string;
      "9 AM": string;
      "10 AM": string;
      "11 AM": string;
      "12 PM": string;
      "1 PM": string;
      "2 PM": string;
      "3 PM": string;
      "4 PM": string;
      "5 PM": string;
      "6 PM": string;
      "7 PM": string;
      "8 PM": string;
      "9 PM": string;
      "10 PM": string;
      "11 PM": string;
      "12 AM": string;
      "1 AM": string;
      "2 AM": string;
      "3 AM": string;
    };
  };
  is_claimed: boolean;
  working_hours: {
    monday: string;
    tuesday: string;
    wednesday: string;
    thursday: string;
    friday: string;
    saturday: string;
    sunday: string;
  };
  status: string;
  scraped_at: string;
  first_seen_at: string;
  website_data: {
    url: string;
    domain: string;
    is_responding: boolean;
    is_empty: string | null;
    title: string;
    meta_keywords: any | null;
    meta_description: string;
    meta_og_title: string;
    meta_og_image: null;
    meta_generator: null;
    lang: string;
    contact_pages: string[];
    facebook: string[] | null;
    youtube: string[] | null;
    twitter: string[] | null;
    instagram: string[] | null;
    linkedin: string[] | null;
    technologies: string[] | null;
    ad_pixels: string[] | null;
    emails: { email: string; sources: string[] }[];
    phones: { phone: string; sources: string[] }[];
    status: string;
    scraped_at: string;
  };
}

export interface SearchPlaces_Params {
  type: string;
  country_code: string;
  admin1_code?: string;
  admin2_code?: string;
  city?: string;
  postal_code?: string;
  skip_data?: 0 | 1;
  per_page?: 1 | 10 | 25 | 50;
  cursor?: string;
  gmap_is_main_type?: 0 | 1;
  gmap_is_closed?: 0 | 1;
  gmap_is_claimed?: 0 | 1;
  gmap_has_website?: 0 | 1;
  gmap_has_phone?: 0 | 1;
  website_has_title?: 0 | 1;
  website_has_meta_keywords?: 0 | 1;
  website_has_meta_description?: 0 | 1;
  website_has_contact_pages?: 0 | 1;
  website_has_emails?: 0 | 1;
  website_has_phones?: 0 | 1;
  website_has_facebook?: 0 | 1;
  website_has_youtube?: 0 | 1;
  website_has_twitter?: 0 | 1;
  website_has_instagram?: 0 | 1;
  website_has_linkedin?: 0 | 1;
  website_has_ad_pixels?: 0 | 1;
  gmap_reviews_count_lte?: string | number;
  gmap_reviews_count_lt?: string | number;
  gmap_reviews_count_gte?: string | number;
  gmap_reviews_count_gt?: string | number;
  gmap_reviews_rating_lte?: string | number;
  gmap_reviews_rating_lt?: string | number;
  gmap_reviews_rating_gte?: string | number;
  gmap_reviews_rating_gt?: string | number;
  gmap_photos_count_lte?: string | number;
  gmap_photos_count_lt?: string | number;
  gmap_photos_count_gte?: string | number;
  gmap_photos_count_gt?: string | number;
  gmap_price_range?: "$" | "$$" | "$$$" | "$$$$";
}

export interface SearchFilters {
  is_main_type?: "0" | "1" | "all";
  is_closed?: "0" | "1" | "all";
  has_website?: "0" | "1" | "all";
  has_phone?: "0" | "1" | "all";
  has_email?: "0" | "1" | "all";
  has_facebook?: "0" | "1" | "all";
  has_instagram?: "0" | "1" | "all";
  has_youtube?: "0" | "1" | "all";
  has_twitter?: "0" | "1" | "all";
  has_linkedin?: "0" | "1" | "all";
  is_claimed?: "0" | "1" | "all";
  price_range?: "all" | "$" | "$$" | "$$$" | "$$$$";
  reviews_rating_lte?: string | undefined;
  reviews_rating_gte?: string | undefined;
  reviews_count_lte?: string | undefined;
  reviews_count_gte?: string | undefined;
  gmap_photos_count_lte?: string | undefined;
  gmap_photos_count_gte?: string | undefined;
  has_contact_pages?: "0" | "1" | "all";
  has_ad_pixels?: "0" | "1" | "all";
}
